spring.datasource.url=jdbc:postgresql://dpg-d6o4dgvkijhs73a1dmc0-a:5432/job_board_db_ac9y
spring.datasource.username=job_board_db_ac9y_user
spring.datasource.password=qcgp64B3Z8pXDV0gh8SRjBUH5iDQGefa

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG






